package ga.aninf.stock.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InventaireAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventaireAllPropertiesEquals(Inventaire expected, Inventaire actual) {
        assertInventaireAutoGeneratedPropertiesEquals(expected, actual);
        assertInventaireAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventaireAllUpdatablePropertiesEquals(Inventaire expected, Inventaire actual) {
        assertInventaireUpdatableFieldsEquals(expected, actual);
        assertInventaireUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventaireAutoGeneratedPropertiesEquals(Inventaire expected, Inventaire actual) {
        assertThat(expected)
            .as("Verify Inventaire auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventaireUpdatableFieldsEquals(Inventaire expected, Inventaire actual) {
        assertThat(expected)
            .as("Verify Inventaire relevant properties")
            .satisfies(e -> assertThat(e.getQuantite()).as("check quantite").isEqualTo(actual.getQuantite()))
            .satisfies(e -> assertThat(e.getInventaireDate()).as("check inventaireDate").isEqualTo(actual.getInventaireDate()))
            .satisfies(e -> assertThat(e.getDeleteAt()).as("check deleteAt").isEqualTo(actual.getDeleteAt()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(actual.getLastModifiedBy()))
            .satisfies(e -> assertThat(e.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(actual.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventaireUpdatableRelationshipsEquals(Inventaire expected, Inventaire actual) {
        assertThat(expected)
            .as("Verify Inventaire relationships")
            .satisfies(e -> assertThat(e.getEntrepot()).as("check entrepot").isEqualTo(actual.getEntrepot()))
            .satisfies(e -> assertThat(e.getProduit()).as("check produit").isEqualTo(actual.getProduit()));
    }
}
